version: 2.1

orbs:
  shipa-orb: shipa/shipa@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0.3
  shellcheck: circleci/shellcheck@2.2.2

executors:
  python:
    resource_class: small
    docker:
      - image: circleci/python:2.7-stretch

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-tests:
    executor: python
    steps:
      - checkout
      - shipa-orb/install
      - run:
          name: Checkout project to build
          command: git clone ssh://git@github.com/shipa-corp/go-sample
      - shipa-orb/app-create:
          appname: jam-orb-test
          platform: go
          team: shipa-admin-team
          framework: shipa-framework
          user: admin@shipa.io
          server: https://af449c0149751464f85ae55e042c0569-1786187615.us-east-2.elb.amazonaws.com:8081
      - shipa-orb/app-deploy:
          source-directory: ./go-sample
          appname: jam-orb-test
          server: https://af449c0149751464f85ae55e042c0569-1786187615.us-east-2.elb.amazonaws.com:8081
          user: admin@shipa.io
      - shipa-orb/app-deploy-canary:
          source-directory: ./go-sample
          appname: jam-orb-test
          server: https://af449c0149751464f85ae55e042c0569-1786187615.us-east-2.elb.amazonaws.com:8081
          user: admin@shipa.io
          canary-steps: 2
          canary-interval: 1m
          canary-step-weight: 50
workflows:
  integration-test_deploy:
    jobs:
      - integration-tests
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          filters:
            branches:
              only: master
          orb-name: shipa/shipa
          publish-version-tag: false
          requires:
            - integration-tests
    when: << pipeline.parameters.run-integration-tests >>

  test-pack:
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: shipa/shipa
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
