description: The official CircleCI CIMG Python Docker image.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: "3.8"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
